export const COMPANY_NAME_MIN_LENGTH = 1
export const COMPANY_NAME_MAX_LENGTH = 50

export const COMPANY_EMAIL_MIN_LENGTH = 5
export const COMPANY_EMAIL_MAX_LENGTH = 50

export const COMPANY_PASSWORD_MIN_LENGTH = 6
export const COMPANY_PASSWORD_MAX_LENGTH = 50

export const COMPANY_PHONE_MIN_LENGTH = 6
export const COMPANY_PHONE_MAX_LENGTH = 14

export const COMPANY_GREATER_NEED_MIN_LENGTH = 32
export const COMPANY_GREATER_NEED_MAX_LENGTH = 1000

export const COMPANY_BUSINESS_SECTOR_MIN_LENGTH = 3
export const COMPANY_BUSINESS_SECTOR_MAX_LENGTH = 50

export const COMPANY_ISO2_MIN_LENGTH = 1
export const COMPANY_ISO2_MAX_LENGTH = 4

export const COMPANY_DIAL_CODE_MIN_LENGTH = 1
export const COMPANY_DIAL_CODE_MAX_LENGTH = 10

export const COMPANY_IDEAS_MIN_LENGTH = 8
export const COMPANY_IDEAS_MAX_LENGTH = 1000
