export const USER_NAME_MIN_LENGTH = 1
export const USER_NAME_MAX_LENGTH = 50
export const USER_EMAIL_MIN_LENGTH = 5
export const USER_EMAIL_MAX_LENGTH = 50
export const USER_PASSWORD_MIN_LENGTH = 6
export const USER_PASSWORD_MAX_LENGTH = 50
